# These are supported funding model platforms

# These are supported funding model platforms

## NOTE: THIS IS A PROTOTYPE BUTTON.
## NOT FOR ACCEPTANCE UNTIL DOMAINS FILED. TAX DOCUMENTS STILL PENDING.

github: [michaelpass]
patreon: eternal_circuit
open_collective: eternal-circuit
ko_fi: eternal_circuit
tidelift: ""
community_bridge: ""
liberapay: eternal_circuit
issuehunt: eternal-circuit
lfx_crowdfunding: ""
polar: eternal-circuit
buy_me_a_coffee: eternalcircuit
thanks_dev: eternal-circuit
custom: ['https://eternal-circuit.com/support', 'https://michaelpass.com/donate']
